home/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.home, name='home'),

    path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'),  # AJAX
]

pomacea/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('mgmt/', include('mgmt.urls')),
    path("accounts/", include("django.contrib.auth.urls")),
]

home/models.py
from django.db import models

inquiryform/models.py
from django.db import models
from django.urls import reverse


class InquiryType(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class State(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class City(models.Model):
    state = models.ForeignKey(State, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class Status(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name


class Inquiries(models.Model):
    date_added = models.DateField(auto_now_add=True)
    first_name = models.CharField(max_length=200, null=True, blank=True)
    last_name = models.CharField(max_length=200, null=True, blank=True)
    middle_name = models.CharField(max_length=200, null=True, blank=True)
    email = models.CharField(max_length=200, null=True, blank=True)
    phone_number = models.CharField(max_length=50, null=True, blank=True)
    mobile_number = models.CharField(max_length=50, null=True, blank=True)
    address = models.TextField(null=True, blank=True)
    state = models.ForeignKey(State, on_delete=models.SET_NULL, null=True)
    city = models.ForeignKey(City, on_delete=models.SET_NULL, null=True)
    zip_code = models.CharField(max_length=200, null=True, blank=True)
    inquiry_type = models.ForeignKey(InquiryType, on_delete=models.SET_NULL, null=True)
    status = models.ForeignKey(Status, default=1, on_delete=models.SET_DEFAULT)

    def get_absolute_url(self):
        return reverse('inquiry_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.first_name + ' ' + self.last_name


class Notes(models.Model):
    inquiries = models.ForeignKey(Inquiries, related_name='notes', on_delete=models.CASCADE)
    date_added = models.DateField(auto_now_add=True)
    body = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.inquiries.first_name + ' ' + self.inquiries.last_name

home/views.py
from django.conf import settings
from django.contrib import messages
from django.core.mail import send_mail
from django.shortcuts import render
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404

from inquiryform.forms import InquiriesForm, City
from inquiryform.models import Inquiries


def home(request):
    if request.method == 'GET':
        form = InquiriesForm()
    else:
        form = InquiriesForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            if Inquiries.objects.filter(email=instance.email).exists():
                messages.warning(request, 'email already exist')
            else:
                instance.save()
                messages.success(request, 'success')
                subject = 'subject here'
                from_email = settings.EMAIL_HOST_USER
                to_email = [instance.email]
                body = 'message here'
                send_mail(subject=subject, from_email=from_email, recipient_list=to_email, message=body,
                          fail_silently=False)

    return render(request, 'home/pages/index.html', {'form': form})


# AJAX
def load_cities(request):
    state_id = request.GET.get('state_id')
    cities = City.objects.filter(state_id=state_id).order_by('name')
    return render(request, 'home/widgets/city_dropdown_list_options.html', {'cities': cities})

home/templates/home/widgets/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Pomacea</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i"
          rel="stylesheet">

    <link href="{% static 'home/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'home/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'home/css/style.css' %}" rel="stylesheet">


<body>

{% block content %}
{% endblock %}

<!-- Vendor JS Files -->
<script src="{% static 'home/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- Template Main JS File -->
<script src="{% static 'home/js/main.js' %}"></script>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_state").change(function () {
        const url = $("#inquiriesForm").attr("data-cities-url");
        const stateId = $(this).val();

        $.ajax({
            url: url,
            data: {
                'state_id': stateId
            },
            success: function (data) {
                $("#id_city").html(data);

            }
        });

    });


</script>

</body>

</html>

home/templates/home/widgets/city_dropdown_list_options.html
<option value="">---------</option>
{% for city in cities %}
<option value="{{ city.pk }}">{{ city.name }}</option>
{% endfor %}